// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InsuranceWebApi
{
    [Table("AppliedPolicy")]
    public partial class AppliedPolicy
    {
        [Key]
        public int ApplicationId { get; set; }
        public int? Pid { get; set; }
        public int? CustId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dateofapplied { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string status { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Reason { get; set; }

        [ForeignKey("CustId")]
        [InverseProperty("AppliedPolicies")]
        public virtual Customer Cust { get; set; }
        [ForeignKey("Pid")]
        [InverseProperty("AppliedPolicies")]
        public virtual policy PidNavigation { get; set; }
    }
}