// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InsuranceWebApi
{
    public partial class policy
    {
        public policy()
        {
            AppliedPolicies = new HashSet<AppliedPolicy>();
        }

        [Key]
        public int Pid { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Pname { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Pcategory { get; set; }
        public int? Totalamount { get; set; }
        public int? Premium { get; set; }
        public int? Tenure { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DOC { get; set; }

        [InverseProperty("PidNavigation")]
        public virtual ICollection<AppliedPolicy> AppliedPolicies { get; set; }
    }
}